### PR TITLE
Fixed "Guru Meditation Error: Core  1 panic'ed (LoadProhibited)"

### PR DESCRIPTION
**Pull request by tantive**
Fixed "Guru Meditation Error: Core  1 panic'ed (LoadProhibited) . Exception was unhandled." (see https://github.com/espressif/esp-idf/issues/1467)

### CODE REVIEW

**Comment by romankc** [comment]
This does not resolve https://github.com/espressif/arduino-esp32/issues/2205 unfortunately.
I don't know if it is related or not.

**Comment by luc-github** [comment]
What is the difference with https://github.com/me-no-dev/AsyncTCP/pull/20 ?

**Comment by luc-github** [comment]
@tantive thank you - please next time state explicitly it is cumulative PR that fix several issues - it allows to close related PR and save @me-no-dev time to check - I close my PR as yours have the fix

**Comment by tantive** [comment]
Seems that the root cause for the Guru Meditation Error was already identified and fixed in the async-mqtt-client:
https://github.com/marvinroger/async-mqtt-client/issues/99
https://github.com/marvinroger/async-mqtt-client/pull/118

@tecteun: fyi

**Pull request merged**
